// <auto-generated />
using System;
using HRS.Infrastructure.Extension;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRS.Infrastructure.migration
{
    [DbContext(typeof(ApplicationdbContext))]
    [Migration("20250726080850_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("HRS.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddUser")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientID")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientID");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HRS.Models.Entities.DaysWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddUser")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeekNO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeekName")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DaysWork");
                });

            modelBuilder.Entity("HRS.Models.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddUser")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LK_SpecialtiesID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LK_SpecialtiesID")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("HRS.Models.Entities.LK_Specialties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialtyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LK_Specialtie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 7, 26, 11, 8, 49, 617, DateTimeKind.Local).AddTicks(634),
                            Description = "Heart..",
                            SpecialtyCode = "CARD",
                            SpecialtyName = "Cardiology",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 7, 26, 11, 8, 49, 617, DateTimeKind.Local).AddTicks(646),
                            Description = "Brain ..",
                            SpecialtyCode = "NEUR",
                            SpecialtyName = "Neurology",
                            Status = true
                        });
                });

            modelBuilder.Entity("HRS.Models.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("HRS.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 7, 26, 8, 8, 49, 617, DateTimeKind.Utc).AddTicks(506),
                            Mobile = "0507319204",
                            Name = "System Admin",
                            Status = true,
                            UserName = "admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 7, 26, 8, 8, 49, 617, DateTimeKind.Utc).AddTicks(510),
                            Mobile = "0551234567",
                            Name = "Doctor Ali",
                            Status = true,
                            UserName = "Doctor",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 7, 26, 8, 8, 49, 617, DateTimeKind.Utc).AddTicks(512),
                            Mobile = "0500206391",
                            Name = "khaled",
                            Status = true,
                            UserName = "Patient",
                            UserTypeId = 3
                        });
                });

            modelBuilder.Entity("HRS.Models.Entities.lK_UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lK_UserType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 7, 26, 11, 8, 49, 617, DateTimeKind.Local).AddTicks(668),
                            Status = true,
                            UserTypeName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 7, 26, 11, 8, 49, 617, DateTimeKind.Local).AddTicks(669),
                            Status = true,
                            UserTypeName = "Doctor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 7, 26, 11, 8, 49, 617, DateTimeKind.Local).AddTicks(671),
                            Status = true,
                            UserTypeName = "Patient"
                        });
                });

            modelBuilder.Entity("HRS.Models.Entities.Appointment", b =>
                {
                    b.HasOne("HRS.Models.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRS.Models.Entities.Patient", "Patients")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRS.Models.Entities.User", null)
                        .WithMany("Appointment")
                        .HasForeignKey("UserId");

                    b.Navigation("Doctor");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("HRS.Models.Entities.DaysWork", b =>
                {
                    b.HasOne("HRS.Models.Entities.Doctor", "Doctor")
                        .WithMany("DaysWork")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HRS.Models.Entities.Doctor", b =>
                {
                    b.HasOne("HRS.Models.Entities.LK_Specialties", "LK_Specialties")
                        .WithOne("Doctor")
                        .HasForeignKey("HRS.Models.Entities.Doctor", "LK_SpecialtiesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRS.Models.Entities.User", null)
                        .WithMany("Doctor")
                        .HasForeignKey("UserId");

                    b.Navigation("LK_Specialties");
                });

            modelBuilder.Entity("HRS.Models.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DaysWork");
                });

            modelBuilder.Entity("HRS.Models.Entities.LK_Specialties", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();
                });

            modelBuilder.Entity("HRS.Models.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HRS.Models.Entities.User", b =>
                {
                    b.Navigation("Appointment");

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
